.TH "include/foo.h" 3 "Sat Nov 23 2019" "Version 0" "KyleCStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/foo.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKyleCStructs::Foo\fP"
.br
.RI "{% Brief Description %} "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBKyleCStructs\fP"
.br
.RI "Contains various data structures\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KyleCStructures from the source code\&.
