.TH "KyleCStructs::Foo" 3 "Sat Nov 23 2019" "Version 0" "KyleCStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KyleCStructs::Foo \- {% Brief Description %}  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <foo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFoo\fP (int a)"
.br
.RI "{% What it do %} "
.ti -1c
.RI "void \fBprintSomething\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
{% Brief Description %} 


.PP
\fBAuthor:\fP
.RS 4
{% Author %} 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "KyleCStructs::Foo::Foo (int a)"

.PP
{% What it do %} 
.PP
\fBPrecondition:\fP
.RS 4
{% Preconditions %} 
.RE
.PP
\fBPostcondition:\fP
.RS 4
{% Postconditions %}
.RE
.PP
\fBParameters:\fP
.RS 4
\fIint\fP a: {% A parameter %}
.RE
.PP
\fBReturns:\fP
.RS 4
{% A thing %}
.RE
.PP
{% Details go here %} 
.SH "Member Function Documentation"
.PP 
.SS "void KyleCStructs::Foo::printSomething ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for KyleCStructures from the source code\&.
