.TH "KyleCStructs" 3 "Sat Nov 23 2019" "Version 0" "KyleCStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KyleCStructs \- Contains various data structures\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFoo\fP"
.br
.RI "{% Brief Description %} "
.in -1c
.SH "Detailed Description"
.PP 
Contains various data structures\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for KyleCStructures from the source code\&.
